/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  BaseController,
  BaseControllerInterface,
} from "../BaseController";

const _abi = [
  "function ownerAddr() view returns (address)",
  "function setManagerAddr(address)",
  "function transferOwnership(address)",
];

export class BaseController__factory {
  static readonly abi = _abi;
  static createInterface(): BaseControllerInterface {
    return new utils.Interface(_abi) as BaseControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseController {
    return new Contract(address, _abi, signerOrProvider) as BaseController;
  }
}
