/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { BaseStorage, BaseStorageInterface } from "../BaseStorage";

const _abi = [
  "function controllerAddr() view returns (address)",
  "function ownerAddr() view returns (address)",
  "function setControllerAddr(address)",
  "function transferOwnership(address)",
];

export class BaseStorage__factory {
  static readonly abi = _abi;
  static createInterface(): BaseStorageInterface {
    return new utils.Interface(_abi) as BaseStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseStorage {
    return new Contract(address, _abi, signerOrProvider) as BaseStorage;
  }
}
