/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ContractManager,
  ContractManagerInterface,
} from "../ContractManager";

const _abi = [
  "function deleteAddress(string)",
  "function getAddress(string) view returns (address)",
  "function ownerAddr() view returns (address)",
  "function setAddress(string,address)",
  "function transferOwnership(address)",
];

export class ContractManager__factory {
  static readonly abi = _abi;
  static createInterface(): ContractManagerInterface {
    return new utils.Interface(_abi) as ContractManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContractManager {
    return new Contract(address, _abi, signerOrProvider) as ContractManager;
  }
}
