/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TweetController,
  TweetControllerInterface,
} from "../TweetController";

const _abi = [
  "function changeVoteInTweet(uint256,int256)",
  "function createTweet(string) returns (uint256)",
  "function ownerAddr() view returns (address)",
  "function setManagerAddr(address)",
  "function transferOwnership(address)",
];

export class TweetController__factory {
  static readonly abi = _abi;
  static createInterface(): TweetControllerInterface {
    return new utils.Interface(_abi) as TweetControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TweetController {
    return new Contract(address, _abi, signerOrProvider) as TweetController;
  }
}
