/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  UserController,
  UserControllerInterface,
} from "../UserController";

const _abi = [
  "function createUser(bytes32,bytes32,bytes32,string,string) returns (uint256)",
  "function ownerAddr() view returns (address)",
  "function setManagerAddr(address)",
  "function transferOwnership(address)",
];

export class UserController__factory {
  static readonly abi = _abi;
  static createInterface(): UserControllerInterface {
    return new utils.Interface(_abi) as UserControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserController {
    return new Contract(address, _abi, signerOrProvider) as UserController;
  }
}
