/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { UserStorage, UserStorageInterface } from "../UserStorage";

const _abi = [
  "function addresses(address) view returns (uint256)",
  "function controllerAddr() view returns (address)",
  "function createUser(address,bytes32,bytes32,bytes32,string,string) returns (uint256)",
  "function ownerAddr() view returns (address)",
  "function profiles(uint256) view returns (uint256, bytes32, bytes32, bytes32, string, string)",
  "function setControllerAddr(address)",
  "function transferOwnership(address)",
  "function usernames(bytes32) view returns (uint256)",
];

export class UserStorage__factory {
  static readonly abi = _abi;
  static createInterface(): UserStorageInterface {
    return new utils.Interface(_abi) as UserStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserStorage {
    return new Contract(address, _abi, signerOrProvider) as UserStorage;
  }
}
